# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #
# 💥                                                                        💥 #
# 💥 Do not edit this file as it will be overwritten!                       💥 #
# 💥                                                                        💥 #
# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #

# See: https://www.terraform.io/docs/backends/types/s3.html
# unfortunately no interpolation
terraform {
  backend "s3" {
    bucket  = "rimu-tf-state"
    key     = "ritdu-ecom-eu1-tf-env/terraform.tfstate"
    region  = "eu-west-1"
    profile = "rimu"

    encrypt    = true
    kms_key_id = "alias/base/s3"

    dynamodb_table = "rimu-tf-state"
  }
}

variable "prefix" {
  default = "ritdu-ecom-eu1"
}

variable "prefix_short" {
  default = "ecom-eu1"
}

variable "app_name" {
  default = "ritdu-ecom-eu1-tf-env"
}
