# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #
# 💥                                                                        💥 #
# 💥 Do not edit this file as it will be overwritten!                       💥 #
# 💥                                                                        💥 #
# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #

# locals can not be overwritten, so anything that is really static should be put in here
locals {
  ns_prefix = compact([var.ns_env_name, var.prefix_short])

  ns_name = "${length(local.ns_prefix) > 0 ? "${join(var.ns_seperator, local.ns_prefix)}." : ""}${var.ns_zone}"

  account_aliases = [
    "ritdu-dcd-eu2",
    "ritdu-pe-eu1",
    "rimu",
    "rimu-prop-vnm",
    "ritdu-dcd",
    "roam-horizon-af1",
    "ritdu-cars-af1",
    "ritdu-jobs-af1",
    "cube-sdc-eu1",
    "ritdu-qme-eu1",
    "ritdu-hex-eu1",
    "ritdu-meta-eu1",
    "ritdu-bi-eu1",
    "ritdu-mkt-eu1",
    "ritdu-ecom-eu1"
  ]

  main_vpc_cidr             = var.vpcs["${var.prefix}.cidr"]
  main_vpc_private_subs     = split(" ", var.vpcs["${var.prefix}.private_subs"])
  main_vpc_database_subs    = split(" ", var.vpcs["${var.prefix}.database_subs"])
  main_vpc_elasticache_subs = split(" ", var.vpcs["${var.prefix}.elasticache_subs"])
  main_vpc_public_subs      = split(" ", var.vpcs["${var.prefix}.public_subs"])
  main_vpc_region           = var.vpcs["${var.prefix}.region"]
  main_vpc_azs              = split(" ", var.vpcs["${var.prefix}.azs"])
  main_vpc_single_natgw     = var.vpcs["${var.prefix}.single_natgw"]
  main_account_id           = var.vpcs["${var.prefix}.account_id"]

  core_account_id = 135132174985

  bastion_ip = "172.16.16.16"
}
