# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #
# 💥                                                                        💥 #
# 💥 Do not edit this file as it will be overwritten!                       💥 #
# 💥                                                                        💥 #
# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #

provider "aws" {
  version = "2.70.0"
  region  = local.main_vpc_region
  profile = "rimu"

  assume_role {
    role_arn = var.prefix == "rimu" ? "" : "arn:aws:iam::${local.main_account_id}:role/administrators"
  }
}

provider "aws" {
  alias   = "ireland"
  version = "2.70.0"
  region  = "eu-west-1"
  profile = "rimu"

  assume_role {
    role_arn = var.prefix == "rimu" ? "" : "arn:aws:iam::${local.main_account_id}:role/administrators"
  }
}

provider "aws" {
  alias   = "virginia"
  version = "2.70.0"
  region  = "us-east-1"
  profile = "rimu"

  assume_role {
    role_arn = var.prefix == "rimu" ? "" : "arn:aws:iam::${local.main_account_id}:role/administrators"
  }
}

provider "aws" {
  alias   = "singapore"
  version = "2.70.0"
  region  = "ap-southeast-1"
  profile = "rimu"

  assume_role {
    role_arn = var.prefix == "rimu" ? "" : "arn:aws:iam::${local.main_account_id}:role/administrators"
  }
}

data "aws_caller_identity" "current" {
}

data "aws_region" "current" {
}

data "aws_availability_zones" "available" {
}

provider "cloudflare" {
  version = "~> 2.0"

  account_id = "6178465172ab2960ec0dcdb25cc5bd49"
  email      = var.cloudflare_email
  api_key    = var.cloudflare_token
}

provider "random" {
  version = "2.1.2"
}

provider "template" {
  version = "2.1.2"
}

provider "null" {
  version = "2.1.2"
}

provider "helm" {
  version = "~> 1.3"
  kubernetes {
    config_path = var.kubectl_config_path
  }
}

provider "kubernetes" {
  version = "~> 1.13"
}
