# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #
# 💥                                                                        💥 #
# 💥 Do not edit this file as it will be overwritten!                       💥 #
# 💥                                                                        💥 #
# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #

variable "region" {
  type    = string
  default = "eu-west-1"
}

variable "vpcs" {
  type = map(string)
}

variable "cloudflare_email" {
  type    = string
  default = ""
}

variable "cloudflare_token" {
  type    = string
  default = ""
}

variable "ns_zone" {
  type    = string
  default = "rimu.ci"
}

variable "ns_zone_id" {
  type    = string
  default = "170681e70ee3036a0d095195c770d8ae"
}

variable "ns_seperator" {
  type    = string
  default = "-"
}

variable "ns_env_name" {
  type    = string
  default = ""
}

variable "key_pair_public" {
  type = string
}

variable "kubectl_config_path" {
  description = "The path to the config file to use for kubectl. If empty, defaults to $HOME/.kube/config"
  type        = string
  default     = "~/.kube/config"
}

variable "office_ips" {
  type = list(string)

  default = [
    "169.255.147.6/32",
    "108.128.7.94/32"
  ]
}

variable "home_ips" {
  type = list(string)

  # Gunter Grodotzki (lifeofguenter)
  # Matthew Nessworthy (matthewnessworthy)
  # Heshamm (heshamelmasry77)
  default = [
    "77.68.17.105/32",
    "213.165.173.138/32",
    "196.151.254.78/32"
  ]
}

variable "backup_window" {
  type    = string
  default = "00:00-02:00"
}

variable "maintenance_window" {
  type    = string
  default = "sat:03:00-sat:05:00"
}
